logo: "recipes_for_oakland_logo_two-line.png"
title: "Recipes"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
aux_links:
  "Recipes for Oakland":
    - "https://tomhillman.github.io/oakland_recipes/"
footer_content: 
  "Copyright &copy; 2021 Mid-Atlantic Planning Team.  Logo by Vexels.com, used with permission. Distributed by an <a href=\"https://www.mit.edu/~amini/LICENSE.md">MIT license.</a>"
