logo: "https://cdn.iconscout.com/icon/premium/png-128-thumb/chef-cap-1505713-1274522.png"
title: "Recipes"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
aux_links:
  "Recipes for Oakland":
    - "//github.com/tomhillman/oakland_recipes/"
