logo: "https://www.vexels.com/media/users/3/224165/isolated/thumb/5b5580f1234bf34aaf8b484a6e79b08b-chef-delivery-logo-by-vexels.png"
title: "Recipes"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
aux_links:
  "Recipes for Oakland":
    - "https://tomhillman.github.io/oakland_recipes/"
footer_content: 
  "Copyright &copy; 2021 Mid-Atlantic Planning Team.  Chef logo by Vexels.com, used with perpmission. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
